/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_929129_12[] = { 0, 1, 2 };

// (before - mean) / scale
const float ei_classifier_anom_scale_929129_12[3] = { 1.0209146644515403, 1.0740722196387358, 1.037823421902828 };
const float ei_classifier_anom_mean_929129_12[3] = { 0.009552186538914813, 0.4715105080274952, 0.0417219494144471 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_929129_12[10] = {
	{ ( float[3] ) { -1.5658528804779053, 0.8359878659248352, 0.9385069608688354 }, 2.077907258898498 },
	{ ( float[3] ) { 0.41760218143463135, 0.9668890237808228, 1.220658779144287 }, 1.522775638822077 },
	{ ( float[3] ) { -0.7906151413917542, 0.9575117230415344, -0.7702484726905823 }, 1.5486147033154427 },
	{ ( float[3] ) { 0.4601573944091797, 0.9091132879257202, -0.799627959728241 }, 1.5559707574540904 },
	{ ( float[3] ) { -0.7508372664451599, -0.936729371547699, 1.2670767307281494 }, 1.752195181845888 },
	{ ( float[3] ) { 0.2355436235666275, -0.8085173964500427, 0.3367464542388916 }, 1.2741443673848396 },
	{ ( float[3] ) { -0.646992027759552, -0.8621441721916199, -0.7846342921257019 }, 1.3158647483654178 },
	{ ( float[3] ) { 0.6192893385887146, -0.8396626710891724, -0.8186936378479004 }, 1.3558736254700114 },
	{ ( float[3] ) { 2.1186492443084717, 0.9107253551483154, 0.7923675179481506 }, 2.138950422150056 },
	{ ( float[3] ) { 0.5363678932189941, -0.8018500804901123, 1.5098915100097656 }, 1.406977733256186 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
