################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/add.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/div.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/if.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/real.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/round.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/select.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/split.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/while.cc \
../edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/add.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/div.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/if.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/real.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/round.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/select.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/split.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/while.d \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/add.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/div.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/if.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/real.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/round.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/select.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/split.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/while.o \
./edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
edge-impulse-sdk/tensorflow/lite/micro/kernels/%.o edge-impulse-sdk/tensorflow/lite/micro/kernels/%.su edge-impulse-sdk/tensorflow/lite/micro/kernels/%.cyclo: ../edge-impulse-sdk/tensorflow/lite/micro/kernels/%.cc edge-impulse-sdk/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I.. -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../Core/Inc -I../edge-impulse-sdk/tensorflow/lite -I../edge-impulse-sdk/third_party/flatbuffers/include -I../edge-impulse-sdk/third_party/gemmlowp -I../edge-impulse-sdk/CMSIS/DSP/Include -I../model-parameters -I../tflite-model -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-edge-2d-impulse-2d-sdk-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-edge-2d-impulse-2d-sdk-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.cyclo
	-$(RM) ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/div.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/div.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/div.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/div.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/if.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/if.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/if.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/if.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.d
	-$(RM) ./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.su
	-$(RM) ./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/real.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/real.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/real.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/real.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/round.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/round.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/round.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/round.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/select.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/select.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/select.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/select.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/split.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/split.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/split.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/split.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.d
	-$(RM) ./edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/while.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/while.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/while.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/while.su ./edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.cyclo ./edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.d ./edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.o ./edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-edge-2d-impulse-2d-sdk-2f-tensorflow-2f-lite-2f-micro-2f-kernels

