################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

C_DEPS += \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 


# Each subdirectory must supply rules for building sources it contributes
edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/%.o edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/%.su edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/%.cyclo: ../edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/%.c edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F407xx -c -I../Core/Inc -I.. -I../edge-impulse-sdk -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../edge-impulse-sdk/tensorflow/lite -I../edge-impulse-sdk/third_party/flatbuffers/include -I../edge-impulse-sdk/third_party/gemmlowp -I../edge-impulse-sdk/CMSIS/DSP/Include -I../model-parameters -I../tflite-model -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-edge-2d-impulse-2d-sdk-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

clean-edge-2d-impulse-2d-sdk-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions:
	-$(RM) ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_no_idx_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmax_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q15.su
	-$(RM) ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_no_idx_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_absmin_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_accumulate_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f16.su
	-$(RM) ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.cyclo
	-$(RM) ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_no_idx_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_mse_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d
	-$(RM) ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f16.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f64.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.su ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.cyclo ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o ./edge-impulse-sdk/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.su

.PHONY: clean-edge-2d-impulse-2d-sdk-2f-CMSIS-2f-DSP-2f-Source-2f-StatisticsFunctions

